intersphinx xref physical types
astropy/sphinx-astropy pull request #40
Opened 2021-05-01 23:13 UTC by nstarman

Signed-off-by: Nathaniel Starkman (@nstarman) <nstarkman@protonmail.com>

Fixes #39

2021-05-01 23:53 UTC, nstarman commented on sphinx_astropy/conf/v1.py
> +# numpydoc_xref_aliases = {}
maybe this should be uncommented?

2021-05-01 23:53 UTC, nstarman commented on sphinx_astropy/conf/v1.py
> +    del ptypes, key, val
del import as well?

2021-05-01 23:53 UTC, nstarman commented on sphinx_astropy/conf/v1.py
> +    "class", 'subclass', "keyword-only", "default", "thereof"
add more from Astropy's conf.py? mixin? Numpy stuff?

2021-05-02 15:48 UTC, nstarman commented on setup.cfg
> +    astropy
add spaces

2021-05-02 15:58 UTC, nstarman commented on sphinx_astropy/conf/v1.py
> +
```suggestion

# aliases to Astropy's physical types. In packages these can be turned on with
# ``numpydoc_xref_aliases.update(numpydoc_xref_aliases_astropy_physical_type)``
```

2021-05-02 18:43 UTC, nstarman commented
https://github.com/astropy/astropy/pull/11684 shows that this will not break astropy due to circular imports.
I don't think this will be super testable until astropy 4.3 is the 'stable' version in the intersphinx connection. @adrn and I have a PR in `gala` to test this when that happens. https://github.com/astropy/astropy/pull/11684 is likewise set up for testing this PR in astropy itself (but that has added complications due to intersphinx).

2021-05-02 20:08 UTC, nstarman commented on sphinx_astropy/conf/v1.py
> +# numpydoc_xref_aliases = {}
yup.

2021-05-02 20:13 UTC, nstarman commented on sphinx_astropy/conf/v1.py
> +    del ptypes, key, val
Done.

2021-05-02 20:17 UTC, nstarman commented on sphinx_astropy/conf/v1.py
> +numpydoc_xref_aliases = {
Add more stuff from astropy's config?

2021-05-02 20:50 UTC, nstarman commented on sphinx_astropy/conf/v1.py
> +    "class", 'subclass', "keyword-only", "default", "thereof"
rm "like" ?

2021-05-02 20:51 UTC, nstarman commented on sphinx_astropy/conf/v1.py
> +        # "readable": ":term:`readable file-like object`",
how many of these should be included?

2021-05-04 20:32 UTC, saimn commented
I'm not convinced about the cross-reference/dependency with astropy, this may cause problems in the future. Could we put a static list instead ? I guess the list doesn't change often so we could avoid the dynamic generation.
Also numpydoc xref should be disabled by default (which is the case here I think), and we could just provide `numpydoc_xref_aliases_astropy_glossary` and `numpydoc_xref_aliases_astropy_physical_type` (no matter the astropy version) and tell people to include what they need in `numpydoc_xref_aliases`.

2021-05-04 21:01 UTC, nstarman commented
> I'm not convinced about the cross-reference/dependency with astropy, this may cause problems in the future.

Do you mean having astropy be a run-time requirement of this package? I was initially concerned (hence astropy/astropy#11684) as I wasn't sure that the local package (astropy) got installed before the documentation requirements, but since it does, there shouldn't be any issues unless the installation order changes.

> Could we put a static list instead ? I guess the list doesn't change often so we could avoid the dynamic generation.

The issue then is that any time astropy wants to update the list, sphinx-astropy needs a new release. Dynamic generation obviates the maintainer burden.

> Also numpydoc xref should be disabled by default (which is the case here I think)

Agreed. It is here. I have a comment explaining how to turn it on.

> and we could just provide `numpydoc_xref_aliases_astropy_glossary` and `numpydoc_xref_aliases_astropy_physical_type` (no matter the astropy version) and tell people to include what they need in `numpydoc_xref_aliases`.

I don't think I understand what you're suggesting here.

One large danger with adding sphinx links to the numpydoc xref regardless of astropy version is that they can cause the docs to fail, depending on the astropy version. I don't think NOT including them will fail a numpydoc xref unless the the docs are built with an earlier version of astropy than is supported in the code.

2021-05-24 21:40 UTC, nstarman commented on sphinx_astropy/conf/v1.py
> +    "class", 'subclass', "keyword-only", "default", "thereof"
Done.

2021-05-24 21:43 UTC, nstarman commented on sphinx_astropy/conf/v1.py
> +numpydoc_xref_aliases = {
I'll hold off until there is a need for more.

2021-05-24 21:48 UTC, nstarman commented on sphinx_astropy/conf/v1.py
> +        # "readable": ":term:`readable file-like object`",
I'm not including any until there is need / I see this pop up in an affiliate package's conf.py.

2021-05-25 00:30 UTC, nstarman commented
ping @astrofrog @pllim @saimn @bsipocz.
I've cleaned up the dynamic generation and now that https://github.com/astropy/astropy/pull/11690 is in, the intersphinx links in ``numpydoc_xref_aliases_astropy_glossary``, and ``numpydoc_xref_aliases_astropy_physical_type`` all programagically work in Astropy without any modifications! It should be convenient for both Astropy and affiliate packages. The Astropy side is ready with https://github.com/astropy/astropy/pull/11684.

2021-05-26 22:12 UTC, astrofrog requested changes
I am in agreement with @saimn that we shouldn't have astropy as a dependency here - instead we should just make use of it if it is installed but not otherwise. For most packages that use this astropy will be a required dependency anyway, and for astropy core we will avoid installing a stable astropy into a development build of the astropy docs.

To be clear, is there any risk of this breaking anything which would warrant a v2 config? I suspect not since this is opt-in, but just wanted to check.

2021-05-26 22:12 UTC, astrofrog commented on sphinx_astropy/conf/v1.py
> +if float(astropy.__version__[:3]) >= 4.3:
We can easily keep Astropy as an optional dependency for this package by defining ASTROPY_INSTALLED further up and only do the following check if it is?

2021-05-27 01:09 UTC, nstarman commented on sphinx_astropy/conf/v1.py
> +if float(astropy.__version__[:3]) >= 4.3:
Thanks @astrofrog. That seems an excellent solution!
I'll make the necessary changes.

2021-06-01 16:02 UTC, nstarman commented
@saimn, I've incorporated the @astrofrog's suggestion to make Astropy an optional dependency. The xref dictionaries are empty if Astropy is not installed or <v4.3 and full otherwise. Does this address the points you raised about cross-dependencies and working around that by static lists?

2021-06-14 20:03 UTC, saimn reviewed
Thanks @nstarman, yes I agree the approach seems reasonable now. Just needs a small change.

2021-06-15 18:14 UTC, nstarman commented on sphinx_astropy/conf/v1.py
> +    "class", "subclass", "keyword-only", "default", "thereof",
Great. I'll push the change.

2021-06-15 18:23 UTC, nstarman commented on sphinx_astropy/conf/v1.py
> +    "class", "subclass", "keyword-only", "default", "thereof",
Done!

2021-06-15 20:06 UTC, saimn approved these changes
Thanks @nstarman, sounds good now.

@astrofrog - Do you want to have another look ?

2021-06-17 16:28 UTC, nstarman commented
I've squashed some unnecessary commits.
Also, I changed the version check from ``float(astropy.__version__[:3]) >= 4.3`` to ``minversion(astropy, "4.3")``. Much cleaner.

2021-06-21 09:01 UTC, merged

2021-06-21 09:01 UTC, saimn commented
Thanks @nstarman !

2021-06-21 16:37 UTC, nstarman commented
Thanks for the reviews!
Now to get this into Astropy. But I guess that will require a new release of sphinx-astropy? Or is there a nightly release or something?

2021-06-21 17:11 UTC, pllim commented
Re: release -- Probably needs a new release but... @saimn , looks like we never set up a auto publish workflow here. Hmm!

2021-06-21 21:11 UTC, saimn commented
Yep, will try to set it up in the coming days.

2021-06-22 20:52 UTC, pllim commented
@nstarman , this is now in https://pypi.org/project/sphinx-astropy/1.4/

2021-06-22 21:21 UTC, nstarman commented
Awesome! Thanks.
Now I can get this in for Astropy main.

2021-06-22 21:39 UTC, pllim commented
Many thanks to @saimn ! 😸